### ISSUE TITLE
Create a basic search bar

### ISSUE THREAD

**Issue by tzimnick** [dandreu7/EventFinder#4]

**Comment by BareRen** [comment]
![Image](https://github.com/user-attachments/assets/5aeba4dd-e5ea-4fe3-80c4-86fad363b171)
User story: As a user I want to be able to use the search bar that filters events by categories and displays relevant results
Scenario: User wants to search for event
Given: The user navigates to the events page
When: The user selects the search bar
And: The user filters the types of events they want to look for
Then: The events page shows the user the kind of events they filtered
